### ISSUE TITLE
Undefined class constant 'PARSE_CONSTANT'

### ISSUE THREAD

**Issue by Zyles** [hassankhan/config#117]
Ran a composer update and now my code is giving 500 error:

````
*125 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Undefined class constant 'PARSE_CONSTANT' in .../vendor/hassankhan/config/src/Parser/Yaml.php on line 30
````

PHP 7.0.31
"hassankhan/config": "*"

**Comment by Zyles** [comment]
I manually added symfony/yaml and it updated from 2.x to 3.x. Seems like composer didn't update the yaml parser version required?

**Comment by DavidePastore** [comment]
Hi @Zyles , `symfony/yaml` is not a required dependency but a suggested one. You can see it [here](https://github.com/hassankhan/config/blob/develop/composer.json) and you can see the related notice [here](https://github.com/hassankhan/config#requirements).
