### ISSUE TITLE
Composer Package is not updated

### ISSUE THREAD

**Issue by jfcherng** [hassankhan/config#119]
https://packagist.org/packages/hassankhan/config is still on `2.0.0`.

**Comment by filips123** [comment]
@DavidePastore @hassankhan Yesterday I tried to publish the new version (2.0.1), but I had some issues. It looks like it was not published correctly. 😞 Can you fix this and let me know how should releases be published?

@jfcherng If you need bug fixes from the latest version, you can use `dev-develop` until release is added.

**Comment by jfcherng** [comment]
Just a FYI, may be related.

The old github-packagist service has been deprecated. Github now uses webhook to trigger packagist to update the version. This is what I encountered months ago when I push a new tag to my own PHP package on Github.

**Comment by DavidePastore** [comment]
@filips123 Unfortunately I can't configure the package in this sense (I don't have the rights to see the Settings tab). I'm sure @hassankhan can look into it.
Just a note to say: once you create a new release, please merge `develop` into `master`, so the `README.md` file and all the content of the repository is updated on the default branch.

**Comment by jfcherng** [comment]
closed because I see `2.0.1` on packagist now :)

**Comment by filips123** [comment]
@DavidePastore I created new release one hour ago but it is again not updated. Branches are also not updated. What's that? Maybe it takes some time to update?

**Comment by filips123** [comment]
Because the version is still not updated, I will reopen the issue.

**Comment by DavidePastore** [comment]
@filips123 The last version is now available. Maybe we have to wait some hours. 😄  https://packagist.org/packages/hassankhan/config

**Comment by filips123** [comment]
@DavidePastore Not hours but days (or week)! 😃 What's this? Versions should be updated instantly.

**Comment by DavidePastore** [comment]
@filips123 I agree with you. I don't know why it takes so much time. Maybe packagist is experiencing some issues.

**Comment by filips123** [comment]
@DavidePastore But other packages seems fine.

Maybe it is because of https://github.com/hassankhan/config/issues/119#issuecomment-460052547. Maybe this repo still uses service which is deprecated (or even removed) so versions aren't updated. But Packagist also maybe manually update versions each week it is now updated.

**Comment by DavidePastore** [comment]
@hassankhan can you please look into it?

**Comment by hassankhan** [comment]
Sorry guys, last time I checked the issue I thought it was resolved. I followed @jfcherng's instructions, please let me know if that fixes it.

**Comment by filips123** [comment]
I'm closing this issue. I will reopen it if needed.
