### ISSUE TITLE
Create first release

### ISSUE THREAD

**Issue by DavidePastore** [hassankhan/config#13]
Hi,
good library. What do you think to create an official release so we can point to a specific one in our composer.json?

Thanks and Regards

**Comment by hassankhan** [comment]
Yeah this should be done asap really, all that's needed is a git tag, if I'm not mistaken

**Comment by DavidePastore** [comment]
Yes, you're right :smile_cat:

**Comment by noodlehaus** [comment]
Yeah. Doing it over the weekend :)

**Comment by noodlehaus** [comment]
first release done, 0.0.1. -- 5ce393a
