### ISSUE TITLE
Drop support for the end of life PHP versions

### ISSUE THREAD

**Issue by nbayramberdiyev** [hassankhan/config#144]
PHP 5.x, 7.0, 7.1, 7.2, and 7.3 reached their end of life and are no longer supported. I suggest the minimum requirement for the project should be raised to PHP 7.4 at least.

If you agree, I'm happy to work on a PR.

**Comment by DavidePastore** [comment]
Hi @nbayramberdiyev. I agree with you. Feel free to work on a PR for it.
