### ISSUE TITLE
Config method merge bug

### ISSUE THREAD

**Issue by shaukei** [hassankhan/config#145]
![image](https://user-images.githubusercontent.com/1581783/154454517-07618d4a-823d-4f18-a7d0-9d6e681b320e.png)

PR:
class AbstractConfig:
    public function merge(ConfigInterface $config)
    {
        $this->data = array_replace_recursive($this->data, $config->all());
+++   $this->cache = [];
        return $this;
    }

**Comment by DavidePastore** [comment]
Hi @shaukei. Thanks for reporting this.
