### ISSUE TITLE
Add Yaml Support

### ISSUE THREAD

**Issue by cryptiklemur** [hassankhan/config#16]
It'd be nice to have

**Comment by hassankhan** [comment]
It would bloat this otherwise tiny library, I think. We could potentially check if the YAML parser extension is enabled and use that, though.

**Comment by cryptiklemur** [comment]
https://github.com/symfony/yaml is less than 300KB. Not very much bloat at all.

**Comment by hassankhan** [comment]
Bloat was probably the wrong word; it adds an extra dependency. Maybe we could add it as a suggested dependency?

**Comment by cryptiklemur** [comment]
You could, but does that extra dependency really hurt anything? Its a small dependency, from a very well supported and amazing author.

**Comment by hassankhan** [comment]
Well, I'll leave the final decision to @noodlehaus, I'd be in favour of having it.

**Comment by DavidePastore** [comment]
:+1

**Comment by noodlehaus** [comment]
yaml support is really something that's good to add, though if we're only going to add it via the symfony package, i think it would be pointless.

for someone who's using yaml for their configurations will already be familiar with symfony's yaml package, and would rather include that package directly.

if we're to add yaml support, going with the PECL extension might be a better choice since it'll make the package an alternative approach to symfony's. it'll also make it consistent with how other formats are supported (built-in functions or pecl extensions).

**Comment by hassankhan** [comment]
I must say from personal experience, the YAML extension can be difficult to get a hold of (on shared hosting) whereas the Symfony package can easily be added as a dependency. 

For practicality's sake, I'd suggest adding the Symfony package as a dependency and the extension as a suggested dependency. We could then do a `function_exists()` check and load whichever is available :smile:

**Comment by noodlehaus** [comment]
I see. But would there be a case where the user would rather require our package, versus just requiring the symfony package directly?

**Comment by cryptiklemur** [comment]
Another library that uses this could support multiple config types 

—
Aaron Scherer
http://bldr.io/

**Comment by hassankhan** [comment]
The Symfony package is literally just a parser, it only allows you to parse YAML files so I think we should use it. We could also check for `ext/yaml` as a fallback, otherwise throw an exception or something?

**Comment by cryptiklemur** [comment]
That fallback would be pointless, if symfony/yaml is a dependency. 

If The extension would parse faster, the the symfony component should be the fallback

—
Aaron Scherer
http://bldr.io/

**Comment by hassankhan** [comment]
Sorry that's what I meant :smile:

**Comment by hassankhan** [comment]
I've pushed a [feature branch](https://github.com/hassankhan/config/tree/feature/add-yaml-support) that does this, should we even check for the extension at all?

**Comment by noodlehaus** [comment]
If so then We probably should just go with the symfony package. I was just about to beg for a pull request 😁

**Comment by hassankhan** [comment]
What do you think then? Shall I merge my feature branch to `develop`? I had a few other things in mind, too, like making it PSR-4 compliant and adding more meaningful exceptions.

**Comment by noodlehaus** [comment]
yup @hassankhan looks awesome! please go ahead :)

**Comment by noodlehaus** [comment]
@hassankhan merge to master anytime you want, by the way.

**Comment by hassankhan** [comment]
Thanks, I will! I was going to add a few more things, I'll push to `develop` when I'm done and let you review it :smile:

**Comment by hassankhan** [comment]
Pushed to `develop`, I've also added exceptions and made the library PSR-4 compliant. Also, maybe we could add Travis tests? It wouldn't take very long to setup :wink: I just need you to set it up from the repo's webhooks settings.

**Comment by hassankhan** [comment]
Also might want to update the repo description to say 'and YAML files'

**Comment by noodlehaus** [comment]
Travis would be great! :D

**Comment by hassankhan** [comment]
Added a `.travis.yml` file, just need you to log into Travis with your GitHub account, and allow it access to GitHub. The next push to any branch should cause a build :smile:

**Comment by noodlehaus** [comment]
awesome, have also signed into and allowed travis access to the repo. also fixed some issues with 5.3, and added the travis badge. tagging this with 0.2.0 and merging to master in a bit.

**Comment by noodlehaus** [comment]
merged and tagged. closing guys.

**Comment by cryptiklemur** [comment]
Thank you sirs!

**Comment by hassankhan** [comment]
Our pleasure :smile:
