### ISSUE TITLE
Parsers performance

### ISSUE THREAD

**Issue by 8ctopus** [hassankhan/config#161]
First of all thank you for creating such a great package, I'm coming from `DotEnv` and I really enjoy what you have built.

I have played with the different parsers and have realized that there is a significant drop in performance with configurations in the Yaml format. It may be worth mentioning it in the README. If you agree, I will create a pull request.

Load configuration was 1ms in both json and php while the same configuration was 5ms with yaml.

**Comment by DavidePastore** [comment]
Hi @8ctopus . Thanks for your feedback. Maybe it would be worth to add a table with a complete benchmark for all the different parsers. What do you think?

**Comment by 8ctopus** [comment]
I would just add a single paragraph about parsers performance not to make the readme much longer.

**Comment by DavidePastore** [comment]
@8ctopus, feel free to create a PR for it 😄
