### ISSUE TITLE
Add neon support

### ISSUE THREAD

**Issue by TomasVotruba** [hassankhan/config#17]
Similar to issue #16. Syntax here: http://ne-on.org/
It's made by/for [Nette framework](https://github.com/nette/nette).
These both issues would make this package usable for almost every framework.

I'd be for standalone repositories with suggestion in composer:
- `noddlehaus/config-yaml`
- `noddlehaus/config-neon`

I can send PR for this support.

**Comment by hassankhan** [comment]
I must say, I've not heard of neon before. Is it widely used by anyone other than Nette?

**Comment by TomasVotruba** [comment]
Not in my knowledge. If that's the requirement, it can be closed.

**Comment by hassankhan** [comment]
I'll let @noodlehaus decide :wink:

**Comment by noodlehaus** [comment]
hi @TomasVotruba, so far the formats that we have in are the commonly used ones. would extending the class and adding the desired support be enough? or do we need to provide a way of injecting support for other formats? also, do we want this to get bigger?

**Comment by TomasVotruba** [comment]
@noodlehaus I think popularity isn't insurance of best quality. This would allow to adopt this package by Nette community. 
I see the package is trying to be minimalistic, and this would require adding at least one new class.

I'm wondering... I would not personally use it, so I'd wait if someone else would have the need (week or so), or close it otherwise.

**Comment by hassankhan** [comment]
Is there a lot of Nette users who want this? It seems trivial to add (just adding [another parser](https://github.com/nette/neon)) but again, only if the community wants/needs it. Leaving this open for another week or so, then closing.

**Comment by TomasVotruba** [comment]
Not really, so not an issue anymore.
