### ISSUE TITLE
Request: Enhancement (Multiple File load)

### ISSUE THREAD

**Issue by pokoot** [hassankhan/config#18]
If possible.

``` php
Config::load([
     'app.php',
     'database.php'
]);

// or load config folder
Config::load(__DIR__ . '/config');

// database.php
<?php
return [
       'default' => 'mysql', 
       'test' => [
             'nested' => 'one'
       ]
];

//Accessing
Config::get('database.default'); // returns mysql
Config::get('database.test.nested'); // returns one

```

If possible and you have enough time. 

Thanks in advance. Kim of Cebu/Singapore ^_^

**Comment by hassankhan** [comment]
Interesting ... but what if there are two config options with the same name? What would happen in that case?

**Comment by noodlehaus** [comment]
hi @pokoot. thanks for the suggestion. @hassankhan can we make newer keys overwrite existing ones, to keep it simple and predictable?

**Comment by hassankhan** [comment]
Totally agree, we should also make it clear in the readme too.

**Comment by VeeeneX** [comment]
And what about connecting two Config files?

**Comment by hassankhan** [comment]
This now works
