### ISSUE TITLE
Setting a value?

### ISSUE THREAD

**Issue by Zyles** [hassankhan/config#23]
I can't seem to update value in a file, what am I doing wrong?

```
<?php

use Noodlehaus\Config as Config;

$config = Config::load($app->config('base_path') . '/config/config.yaml');
$next_number = $config->get('accounting.next_number');
$new_number = ++$next_number;
$config->set('accounting.next_number', $new_number);
```

I can return the get value so the file is readable etc. But it wont update the value in the file.

**Comment by hassankhan** [comment]
By design, Config won't overwrite a text file, it will only overwrite that value in-memory.
