### ISSUE TITLE
Symfony Yaml::parse File input deprecated

### ISSUE THREAD

**Issue by jenolan** [hassankhan/config#25]
> Deprecated: The ability to pass file names to the Symfony\Component\Yaml\Yaml::parse method is deprecated since version 2.2 and will be removed in 3.0. Pass the YAML contents of the file instead

Recommend just adding a file_get_contents for the file and feed the returned text into the method.

**Comment by hassankhan** [comment]
Thank you very much for bringing this to our attention :+1:
