### ISSUE TITLE
Time for a new release?

### ISSUE THREAD

**Issue by hassankhan** [hassankhan/config#31]
Should have probably incremented as we ticked off items from #26. Opinions on skipping a few minor versions and going to 0.9?

**Comment by hassankhan** [comment]
Or, alternatively, can just merge specific commits from `develop` into `master` and tag those? Going by number of significant changes, we'll be up to 0.7

**Comment by noodlehaus** [comment]
Yes we can pick some of develop into master instead, and tag. Not able to do much atm as work is eating me up.

**Comment by hassankhan** [comment]
No worries, I'm happy taking care of it :+1:
