### ISSUE TITLE
HHVM support

### ISSUE THREAD

**Issue by hassankhan** [hassankhan/config#35]
Currently one test [is failing](https://travis-ci.org/noodlehaus/config/jobs/52027342) (something about INI files). It's probably worth the effort to fix it, just cos :wink:

**Comment by tomzx** [comment]
when `parse_ini_*` is called in hhvm, if an error occurs during parsing, this error is not available to `error_get_last`.

I've filled https://github.com/facebook/hhvm/issues/5526 to track the issue.

**Comment by hassankhan** [comment]
Hi, thanks for filing an issue. Let's see what they say :smile:

**Comment by tomzx** [comment]
It's been about 6 months now and the issue hasn't been acknowledged. It's probably safe to assume it won't be fixed anytime soon.

I suggest we make ini parsing disabled on hhvm until then. This would mean updating the test suite to skip the related tests if executed under hhvm.

**Comment by hassankhan** [comment]
Yep, agree with you - not quite sure how to do it though

**Comment by tomzx** [comment]
In the related tests

```
if(defined('HHVM_VERSION'))   $this->markTestSkipped(); 
```

To disable ini parsing, I guess we could simply filter the list of Config::$supportedFileParsers and remove it.

It might also be worthwhile writing a little test that will show that ini parsing will not work under hhvm (so that we may be advised if they ever fix it).
