### ISSUE TITLE
Defaults not loading

### ISSUE THREAD

**Issue by ti0rafa** [hassankhan/config#37]
It seems that the Config class is missing an array_merge() like the AbstractConfig does. 

Right now if I add a default configuration, it will get ignore since $this->data is not merge with the getDefaults() method.

**Comment by hassankhan** [comment]
Do you have any example code that doesn't work?

**Comment by hassankhan** [comment]
If you're creating an object to hold default values, you should be extending `AbstractConfig` directly. That said, I think I know how to fix it

**Comment by ti0rafa** [comment]
Do you still need an example?.

If I extend from `AbstractConfig` then the constructor doesn't load the config file (JSON, etc), that logic is on the `Config` class. Thats why im extending directly from `Config`.

I wanted to do this: create a class with the default values, then load a config file. If a value was not set in the file then it will just load what ever default it had in the created class.

**Comment by hassankhan** [comment]
You make a fair point, I'll push a fix live later

**Comment by ti0rafa** [comment]
Thanks, I'm looking forward to it.

**Comment by hassankhan** [comment]
Could you try again using the `develop` branch?

**Comment by ti0rafa** [comment]
Cool its working now, thanks

**Comment by hassankhan** [comment]
Awesome, I'll tag a new release then :)
