### ISSUE TITLE
[Yaml] Warnings emitted if configuration file is empty

### ISSUE THREAD

**Issue by tomzx** [hassankhan/config#44]
When constructing a new Config object, if the target file is empty, the following two warnings are emitted:

```
Warning: array_replace_recursive(): Argument #2 is not an array in src/Config.php on line 65
Warning: array_merge(): Argument #2 src/AbstractConfig.php on line 39
```

https://github.com/hassankhan/config/blob/b7ab317fadaf6cee0e3bcd48367b964c00db4482/src/Config.php#L65

```
$this->data = array_replace_recursive($this->data, $parser->parse($path));
```

This is due to the fact that the Yaml parser will return null if the file is empty (thus not an array). An "easy" fix would be to cast the result of $parser->parse($path) to an array:

```
$this->data = array_replace_recursive($this->data, (array)$parser->parse($path));
```

What do you think?

**Comment by DavidePastore** [comment]
Nice catch! Can you create a PR with this check (and a related test)?
