### ISSUE TITLE
Wrong @return Noodlehaus\File\FileInterface ...

### ISSUE THREAD

**Issue by ntd1712** [hassankhan/config#49]
Please check here https://github.com/hassankhan/config/blob/master/src/Config.php#L76
It's the "Noodlehaus\FileParser\FileParserInterface" instead of the "Noodlehaus\File\FileInterface", right?

**Comment by DavidePastore** [comment]
Yes, I think you're right. Can you build a PR on this?

**Comment by ntd1712** [comment]
What does PR mean? You meant "public repo", right?
Actually, it still works fine, I need do nothing. All the rest things are based on them.

**Comment by DavidePastore** [comment]
What I mean with PR is Pull Request. You can fork the project, edit the file and send us a pull request that we will be happy to merge.

**Comment by ntd1712** [comment]
:+1:

**Comment by DavidePastore** [comment]
Closed in c29e3c58ffbe1690a1c115c1892727596b322672
