### ISSUE TITLE
Change visibility of class attributes

### ISSUE THREAD

**Issue by hassankhan** [hassankhan/config#5]
I really like your library. I wanted to have a default Config object, and I thought it'd be easier to extend the `Noodlehaus\Config` object and then set `$this->data` to my data.

Unfortunately, I can't currently do this because `$this->data` is a private attribute. Do you think I could make a PR and change this?

**Comment by noodlehaus** [comment]
Hi Hassan. Yes, please do. Would appreciate the pull :)

**Comment by hassankhan** [comment]
I kinda did this in the PR #6, shall we just close this one? Sorry :blush:

**Comment by noodlehaus** [comment]
Yeah, merged it. Thank you very much! :)
