### ISSUE TITLE
Cannot easily chain config object data.

### ISSUE THREAD

**Issue by kwhat** [hassankhan/config#59]
Hi, I was wondering if [src/Config.php#L55](https://github.com/hassankhan/config/blob/master/src/Config.php#L55) was an oversight? It makes inheriting the previous config more difficult that it should be:

```
class Config extends \Noodlehaus\Config
{
    protected function getDefaults()
    {
        static $buffer = array();
        $data = $buffer;

        $buffer = array_replace_recursive($buffer, $this->data);

        return $data;
    }
}
```

The only other thing I can think of is re-implementing the entire Noodlehaus\Config class.

**Comment by hassankhan** [comment]
Well, the idea was that if you need a specific Config object with preset defaults, then you should extend `AbstractConfig`.

**Comment by kwhat** [comment]
That's what I ended up doing.  Feel free to close as question.  Thanks.
