### ISSUE TITLE
Set PHP 5.5.9 as minimum required version

### ISSUE THREAD

**Issue by hassankhan** [hassankhan/config#75]
PHP 5.3 is ... outdated to say the least.

Since the library is fairly mature, I think maybe we should do any last tidy ups, then do a 1.0 release with 5.5.9 set. That way, anyone still using older versions can use <1.0 and still be fine (I think)

**Comment by DavidePastore** [comment]
I think it's ok to change the minimum required version of PHP but is there a reason behind this choice?

**Comment by hassankhan** [comment]
Yep, reason being any version of PHP older than 5.5 are outdated, and users are not recommended to be running them.

**Comment by DavidePastore** [comment]
Let's do this :dancer:

**Comment by Potherca** [comment]
Any news on this?

**Comment by DavidePastore** [comment]
Closed by #99.
