### ISSUE TITLE
Add remove() method

### ISSUE THREAD

**Issue by hassankhan** [hassankhan/config#76]
**hides**

I _know_ we've talked about [this](https://github.com/hassankhan/config/issues/10) [before](https://github.com/hassankhan/config/pull/36), and I _know_ we decided it went against the spirit of the project etc.  **BUT** I think it may be time. :+1:  

I have a use-case where I load a JSON representation of an access token from my Config, instantiate as an `AccessToken` and put it back. In my `getDefaults()`, I specify  `null` for the `access_token`.

If no access token is provided, I'd prefer the `access_token` weren't available, but guess what? `$config ->has('access_token')` returns `true` - which isn't unexpected behaviour, this is what we wanted.

One way of fixing it is to run `array_filter()` over the defaults in the subclass ... or should we move that to the `AbstractConfig`?

Another would be to add the `remove()` method which would actually remove the **key**. :smile: 

I realise now that I'm describing two different issues here, apologies for the ramble.

**Comment by DavidePastore** [comment]
I think that create a `remove()` method that simply remove the key would be a nice solution.

**Comment by hassankhan** [comment]
Cool, then that's the way forward :+1:

**Comment by DavidePastore** [comment]
@hassankhan Can we consider closed this issue?

**Comment by hassankhan** [comment]
Oh yeah, totally
