### ISSUE TITLE
Broken tests

### ISSUE THREAD

**Issue by 0x6B386F** [hassankhan/config#78]
PHPUnit 5.3.4 by Sebastian Bergmann and contributors.

Runtime:       PHP 5.6.20-0+deb8u1
Configuration: /home/onedal/devel/onedal/config/phpunit.xml.dist
Error:         No code coverage driver is available

...............................................F................  64 / 64 (100%)

Time: 121 ms, Memory: 12.25Mb

There was 1 failure:

1) Noodlehaus\FileParser\Test\JsonTest::testLoadInvalidJson
Failed asserting that exception message 'quoted object property name expected' contains 'Syntax error'.

FAILURES!
Tests: 64, Assertions: 127, Failures: 1.

**Comment by hassankhan** [comment]
According to [Travis](https://travis-ci.org/hassankhan/config), our tests are running fine. Can you check your environment please? Thanks

**Comment by DavidePastore** [comment]
Closing due inactivity.
