### ISSUE TITLE
Implement ArrayAccess

### ISSUE THREAD

**Issue by hassankhan** [hassankhan/config#8]
Not sure if you'd want this in the library, but we could implement the ArrayAccess interface to allow for array-style get-set operations. The following would both be the same thing:

``` php
$config->get('key');
$config['key'];
```

**Comment by noodlehaus** [comment]
Yes, this is something I was working on before but didn't really get to finish it. With it, the following behaviour should also work:

``` php
$config->get('key.subkey');
$config['key']['subkey'];
$config['key.subkey'];
```

Also need to decide if writes would be allowed (should work if get()s return references).

**Comment by hassankhan** [comment]
Okay, I'll create a branch and push it, I have code which works for 

``` php
$config->get('key.subkey');
$config['key.subkey'];
```

Should be easy to add something for `$config['key']['subkey'];`

**Comment by hassankhan** [comment]
Whoops, accidentally closed the issue

**Comment by hassankhan** [comment]
Started work on it [here](https://github.com/hassankhan/config/tree/feature/implement-arrayaccess)

**Comment by noodlehaus** [comment]
great! hassan, you want me to add you as a collaborator? it would be great for the library.

**Comment by hassankhan** [comment]
Yeah sure that'd be awesome!

**Comment by noodlehaus** [comment]
ok added :) thanks!

**Comment by hassankhan** [comment]
Making the last PR now, gonna close this issue :smile:
