### ISSUE TITLE
filtering?

### ISSUE THREAD

**Issue by aolko** [hassankhan/config#84]
how to get an item, for example, where key = 1

```
{
  "items":[
    {
      "key":"0",
    },
    {
      "key":"1"
    }
  ]
}
```

**Comment by hassankhan** [comment]
Sorry, can you explain with some more context? Not quite sure what you're asking

**Comment by aolko** [comment]
select all the config items **where key = 1**

**Comment by hassankhan** [comment]
Ahh okay, that is outside the scope of the project currently, I'm not aware of any plans to add it and personally don't think it is necessary. I'm open to changing my mind if @DavidePastore or any other contributors see value in adding it, though.

**Comment by DavidePastore** [comment]
@hassankhan I agree with you, this seems unrelated to the project.

**Comment by hassankhan** [comment]
Cool, thanks for your input @DavidePastore, sorry @aolko, it's just not something we see as useful for this project.
