### ISSUE TITLE
error parsing .ini files that contain zero parsable data

### ISSUE THREAD

**Issue by gbhorwood** [hassankhan/config#86]
running unit tests for my project which uses Noodlehaus\Config, i was presented with this error while attempting to parse an .ini file that contained no parsable content.

TypeError: Argument 1 passed to Noodlehaus\Exception\ParseException::__construct() must be of the type array, null given

this ocurred in php 7.0.8 with the content of the test .ini file being 'no parsable content'.

investigating showed the issue appears to happen because parse_ini_file() returns null if there is no ini-style syntax in the target file, but does not set an error, leaving error_get_last() to return NULL which, being a non-array, causes ParseException to fail when thown.

i have a pr with the fix for your consideration. apologies in advance if my pr submission procedure isn't perfect; i live in a bitbucket/mercurial bubble and confess i struggle somewhat with git.

love the project!

**Comment by DavidePastore** [comment]
Hi @gbhorwood , thanks for your interest in the project. I really appreciate it. You're right about the issue. Nice catch!

**Comment by DavidePastore** [comment]
Closed by #87 .
