### ISSUE TITLE
i got file not found expection for config file

### ISSUE THREAD

**Issue by charan5551** [hassankhan/config#92]
```
Fatal error: Uncaught exception 'Noodlehaus\Exception\FileNotFoundException' with message ' in C:\wamp64\www\autentication\vendor\hassankhan\config\src\Config.php on line 153
```
this is was my code:
```php
<?php
use Slim\Slim;
use Noodlehaus\Config;
session_cache_limiter(false);
session_start();

ini_set('display_errors', 'on');

define('INC_ROOT', dirname(__DIR__));

require INC_ROOT .'/vendor/autoload.php';
require_once INC_ROOT . '/vendor/hassankhan/config/src/Config.php';

$app = new Slim([
	'mode' => file_get_contents(INC_ROOT . '/mode.php')
]);
echo $app->config('mode');
$app->configureMode($app->config('mode'), function() use ($app) {
	$app->config = Config::load(INC_ROOT . "/app/config/{$app->mode}.php");
});


?>
```

**Comment by charan5551** [comment]
this was the error i got

![capture](https://cloud.githubusercontent.com/assets/28190887/25562132/67eacdca-2d9a-11e7-8123-62bafc09e0ff.PNG)

**Comment by charan5551** [comment]
can you please respond any one for this error  i stucked in that  project due to error.plz help me i already added hassankhan/config
![capture](https://cloud.githubusercontent.com/assets/28190887/25562154/23c1c742-2d9b-11e7-8617-e978b1523cdf.PNG)
 this was the my total project
![capture](https://cloud.githubusercontent.com/assets/28190887/25562142/de2bd57e-2d9a-11e7-8cb7-80289e747737.PNG)

**Comment by hassankhan** [comment]
From the screenshots you've provided, no file exists at `autentication/app/config/development.php`.

**Comment by charan5551** [comment]
Oh tq so much

**Comment by charan5551** [comment]
I wil see now
