### ISSUE TITLE
Package depends on Symfony/Yaml but it is only suggest?

### ISSUE THREAD

**Issue by bfday** [hassankhan/config#97]
This [file](https://github.com/hassankhan/config/blob/master/src/FileParser/Yaml.php) shows that this package requires Symfony\Component\Yaml\Yaml but it's only a suggest in composer.json
`
"suggest": {
        "symfony/yaml": "~2.5"
    },
`
is it ok? Seems that it's a requirement not only a suggestion.

**Comment by DavidePastore** [comment]
Hi @bfday. `symfony/yaml` is used only when you need to parse YAML files. I think not everybody has this need, but in the case one has, we should explicitly indicate it. Maybe @hassankhan could give a more detailed explanation.

**Comment by hassankhan** [comment]
Pretty much what @DavidePastore said - if a user needs to parse YAML files, they'd need to also install the `symfony/yaml` package, otherwise users would get an unnecessary package installed.

**Comment by DavidePastore** [comment]
Added a more explicit reference about the `symfony/yaml` requirement in #102.
